Vaisseaux:
  # carbone - Puces - Hydrogène - lvl du sp
  Croiseur : 
   - 75
   - 50
   - 10
   - 1
  Nano-Sonde : 
   - 5
   - 50
   - 50
   - 3
  Cargo : 
   - 200
   - 75
   - 150
   - 5
  Victoire : 
   - 250
   - 200
   - 150
   - 8
  Colonisateur : 
   - 1500
   - 1500
   - 2000
   - 10

Infra:
  # carbone - Puces - Hydrogène
  Carbone : 
   - 10
   - 5
   - 5
  Puces : 
   - 4
   - 9
   - 7
  Hydro : 
   - 10
   - 8
   - 2
  Lab : 
   - 4
   - 10
   - 10
  Sp : 
   - 10
   - 10
   - 10
