Vaisseaux:
  # carbone - Puces - Hydrogène - lvl du sp - Puissance - Capacité de transport
  Croiseur :
   - 75
   - 50
   - 10
   - 1
   - 25
   - 10
  Nanosonde :
   - 5
   - 50
   - 50
   - 3
   - 1
   - 0
  Cargo :
   - 200
   - 75
   - 150
   - 5
   - 1
   - 100
  Victoire :
   - 250
   - 200
   - 150
   - 8
   - 75
   - 20
  Colonisateur :
   - 1500
   - 1500
   - 2000
   - 10
   - 1
   - 30

Infra:
  # carbone - Puces - Hydrogène-Spatioport - Radar
  Carbone :
   - 10
   - 5
   - 5
  Puces :
   - 4
   - 9
   - 7
  Hydro :
   - 10
   - 8
   - 2
  Sp :
   - 11
   - 9
   - 11
  Rad :
   - 8
   - 12
   - 12
